<?php

/**
 * @file
 * Contains bhcc_alert_banner.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bhcc_alert_banner_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bhcc_alert_banner module.
    case 'help.page.bhcc_alert_banner':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Alert Banners Support module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements HOOK_module_implements_alter
 */
function bhcc_alert_banner_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    // Move bhcc alert banners to last hook
    unset($implementations['bhcc_alert_banner']);
    $implementations['bhcc_alert_banner'] = null;
  }
}

/**
 * Implements HOOK_entity_build_defaults_alter
 */
function bhcc_alert_banner_entity_build_defaults_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, $view_mode) {

  // ECK entities don't implement getType()
  if ($entity->bundle() == 'alert_banner') {

    // Set a cache context based on the hide alert banner cookie token
    $build['#cache']['contexts'][] = 'cookies:hide-alert-banner-token';
    $build['#cache']['contexts'][] = 'user.roles:anonymous';
    $build['#cache']['contexts'][] = 'session';

    // Set a cache context based on if on the front page
    $build['#cache']['contexts'][] = 'url.path:is_front';

    // Get token and use as a cache tag
    $token = \Drupal::service('bhcc_alert_banner.state')->getToken();
    $build['#cache']['tags'][] = 'bhcc.alert.banner.token:'.$token;

    // We need to switch off (static) page cache here for individual anon users.
    // They still get the dynamic page cache, handled by the cache contexts.
    // Should be a better way of handling this?
    // \Drupal::service('page_cache_kill_switch')->trigger();
  }
}

/**
 * Implements HOOK_preprocess_eck_entity
 */
function bhcc_alert_banner_preprocess_eck_entity(&$variables) {

  if ($variables['entity_type'] == 'alert_banner') {

    // Get token
    $token = \Drupal::service('bhcc_alert_banner.state')->getToken();

    // Get cookie
    $cookie = \Drupal::request()->cookies->get('hide-alert-banner-token');

    // Add a hidden class
    $variables['attributes']['class'][] = 'hidden';

    // Token as attribute
    $variables['attributes']['data-dismiss-alert-token'] = $token;

    // Ensure token is accessible by javascript.
    $variables['#attached']['drupalSettings']['bhcc_alert_banner']['token'] = $token;
  }
}

/**
 * Implements HOOK_alert_banner_create
 */
function bhcc_alert_banner_alert_banner_create(Drupal\Core\Entity\EntityInterface $entity) {
  _bhcc_alert_banner_alert_banner_save($entity);
}

/**
 * Implements HOOK_alert_banner_update
 */
function bhcc_alert_banner_alert_banner_update(Drupal\Core\Entity\EntityInterface $entity) {
  _bhcc_alert_banner_alert_banner_save($entity);
}

/**
 * Common function when aler banner entity saved
 */
function _bhcc_alert_banner_alert_banner_save(Drupal\Core\Entity\EntityInterface $entity) {

  // Check if the entity is flagged as live
  $flag = \Drupal::service('flag')->getFlagById('put_live');
  if (!empty($flag))  {
    $flaggings = \Drupal::service('flag')->getEntityFlaggings($flag, $entity);

    if (!empty($flaggings)) {

      // Regenerate a JS token for the updated alert banner
      \Drupal::service('bhcc_alert_banner.state')->generateToken($entity)->save();
    }
  }

  // Better to use cache tags instead of doing a full flush?
  drupal_flush_all_caches();
}

/**
 * Implements HOOK_form_alter
 */
function bhcc_alert_banner_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Edit the alert banner entity form on the creation or edit mode
  if ($form_id == 'alert_banner_alert_banner_form' || $form_id == 'alert_banner_alert_banner_edit_form') {

    // Create the vertical tabs like on node edit forms
    // @src https://drupal.stackexchange.com/a/276907
    $form['#theme'][] = 'node_edit_form';
    $form['#attached']['library'] = ['node/drupal.node'];
    $form['advanced'] = [
      '#type' => 'container',
      '#weight' => 99,
      '#attributes' => [
        'class' => ['entity-meta'],
      ],
    ];

    // Add elbow room libary
    $form['#attached']['library'][] = 'elbow_room/base';
    $elbowRoomConfig = Drupal::configFactory()->get('elbow_room.settings');
    $form['#attached']['drupalSettings']['elbow_room']['default'] = $elbowRoomConfig->get('default');

    // Add node form classes for elbow room to function
    $form['#attributes']['class'][] = 'node-form';

    // Set authoring information into sidebar
    $form['author'] = [
      '#type' => 'details',
      '#title' => t('Authoring information'),
      '#group' => 'advanced',
      '#weight' => 90,
      '#optional' => 1,
      '#open' => true,
      '#attributes' => [
        'class' => ['entity-form-author'],
      ],
    ];

    // Move the authoring info into sidebar like nodes
    $form['uid']['#group'] = 'author';
    $form['created']['#group'] = 'author';

    // Change the Title label
    // unset($form['title']['widget'][0]['#description']);
    unset($form['title']['widget'][0]['value']['#description']);

    // Change the Link text description
    $form['field_alert_link']['widget'][0]['title']['#description'] = t("If you don't write anything here, we will use: More information");

    // Set the flags details group to open and change title
    $form['flag']['#open'] = true;
    $form['flag']['#title'] = t('Publishing options');
    unset($form['flag']['#group']);

    // Change put live description
    $form['flag']['put_live']['#description'] = t('Tick this box to put the banner on our website.').'<br>'.t('Untick this box if you want to remove the banner from the website.');
  }
}

/**
 * Implements hook_theme().
 */
function bhcc_alert_banner_theme() {
  return [
    // Bundle our template with the module (which can be overridden in theme)
    'eck_entity__alert_banner' => [
      'base hook' => 'eck_entity',
    ],
  ];
}
